

export const userSignUp=(req,res)=>{
    try {
        console.log(req.body);
    } catch (error) {
        console.log("error from back")
    }
};